### ISSUE TITLE
Piccoli problemi in integrazione con FExplorer

### ISSUE THREAD

**Issue by carloBarazzetta** [MuzioValerio/HtmlToPdf#1]
Ciao Valerio, nel compilare il progetto demo per provare a integrarlo in FExplorer ho visto che manca SynPDF in ThirdParties, l'ho recuperata da Git, ma sarebbe comodo se l'aggiungessi e se la demo avesse le path relative a ThirdParties così uno la compila al volo.
Altra cosa non c'è il file Vista.res che richiede la main form, non so se è indispensabile, l'ho remmato e compila ugualmente.
Infine se compilo con 10.4 (ma credo capiti anche con altre versioni di Delphi) ho qualche hint di variabili non utilizzate o inizializzazioni inutili e dei warning di implicit string cast from AnsiString to string (quando casti con PDFString... non so se è corretto. Nella mia versione ho fatto un po' di pulizia.
L'ho già parzialmente integrata ;-)

**Comment by MuzioValerio** [comment]
Ciao Carlo il mio nome di battesimo è Muzio sarei felice se mi chiamassi così ;).
Ho ricevuto le tue segnalazioni, le ho verificate.
Effettivamente il file Vista.res non è necessario, è un refuso del progetto originale del 2010 (dichiarato morto) da cui sono partito.
Ho anche verificato i Warning di cast implicito.
Effettivamente non è necessario effettuare il cast se utilizzi la classe TpdfDocumentGDI, quindi, ho eliminato il cast e corretto il codice.
Ho anche corretto AddPage che impostava una variabile lPage che non veniva poi utilizzata, con la più corretta, Self.AddPage, che istanzia una nuova pagina nel documento.

**Comment by carloBarazzetta** [comment]
Perfetto, grazie mille. Chissa quanti leggendolo avranno invertito il nome e il cognome come ho fatto io. Perdonami ma non l'ho fatto apposta, giuro, "mano sul fuoco". ;-)
Ho già integrato il tutto in FExplorer e sarò lieto di menzionare il tuo contributo martedì al Delphi Day.
